# Generated by Django 5.2.7 on 2025-11-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('endereco', models.TextField(max_length=100, verbose_name='Endereço')),
                ('horario_de_abertura', models.TimeField(verbose_name='Horário de Abertura')),
                ('horario_de_fechamento', models.TimeField(verbose_name='Horário de Fechamento')),
            ],
            options={
                'verbose_name': 'cinema',
                'verbose_name_plural': 'cinemas',
                'ordering': ['id'],
            },
        ),
    ]
